import type {
  EverydayUserProfile,
  RiskScoreHistory,
  BudgetCategory,
  RiskScenario,
  TimelineEvent,
  EmergencyPlan,
  SpendingDataPoint,
  InsightCard,
  AIMessage,
} from '@/types'

export const everydayProfile: EverydayUserProfile = {
  id: 'user-001',
  name: 'Alex Rivera',
  email: 'alex@example.com',
  monthlyIncome: 7200,
  monthlyExpenses: 5150,
  savingsBalance: 11400,
  emergencyFundTarget: 21600, // 3 months expenses
  riskScore: 42,
  riskLevel: 'medium',
  memberSince: '2024-01-15',
  plan: 'plus',
}

export const riskScoreHistory: RiskScoreHistory[] = [
  { date: '2025-11', score: 55 },
  { date: '2025-12', score: 51 },
  { date: '2026-01', score: 48 },
  { date: '2026-02', score: 53 },
  { date: '2026-03', score: 49 },
  { date: '2026-04', score: 45 },
  { date: '2026-05', score: 42 },
]

export const budgetCategories: BudgetCategory[] = [
  {
    id: 'housing',
    name: 'Housing',
    budgeted: 1800,
    actual: 1800,
    icon: 'home',
    trend: 'stable',
    changePercent: 0,
  },
  {
    id: 'food',
    name: 'Food & Dining',
    budgeted: 600,
    actual: 742,
    icon: 'utensils',
    trend: 'up',
    changePercent: 23.7,
  },
  {
    id: 'transport',
    name: 'Transportation',
    budgeted: 450,
    actual: 387,
    icon: 'car',
    trend: 'down',
    changePercent: -14.0,
  },
  {
    id: 'health',
    name: 'Health & Fitness',
    budgeted: 200,
    actual: 215,
    icon: 'heart-pulse',
    trend: 'up',
    changePercent: 7.5,
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    budgeted: 300,
    actual: 418,
    icon: 'tv',
    trend: 'up',
    changePercent: 39.3,
  },
  {
    id: 'utilities',
    name: 'Utilities',
    budgeted: 280,
    actual: 264,
    icon: 'zap',
    trend: 'down',
    changePercent: -5.7,
  },
  {
    id: 'savings',
    name: 'Savings',
    budgeted: 720,
    actual: 720,
    icon: 'piggy-bank',
    trend: 'stable',
    changePercent: 0,
  },
  {
    id: 'subscriptions',
    name: 'Subscriptions',
    budgeted: 120,
    actual: 161,
    icon: 'refresh-cw',
    trend: 'up',
    changePercent: 34.2,
  },
]

export const riskScenarios: RiskScenario[] = [
  {
    id: 'scenario-001',
    title: 'Car Breakdown',
    description:
      'Major mechanical failure requiring transmission or engine repair, leaving you without primary transportation for 1–3 weeks.',
    probability: 22,
    impact: 68,
    riskLevel: 'medium',
    category: 'Vehicle',
    estimatedCost: 3200,
    preparednessScore: 35,
    tags: ['vehicle', 'transportation', 'high-cost'],
    lastUpdated: '2026-05-10',
    monthlyImpact: 267,
  },
  {
    id: 'scenario-002',
    title: 'Medical Emergency',
    description:
      'Unexpected hospitalization or surgery not fully covered by insurance, resulting in out-of-pocket expenses.',
    probability: 15,
    impact: 85,
    riskLevel: 'high',
    category: 'Health',
    estimatedCost: 6500,
    preparednessScore: 20,
    tags: ['health', 'insurance', 'critical'],
    lastUpdated: '2026-05-12',
    monthlyImpact: 541,
  },
  {
    id: 'scenario-003',
    title: 'Job Loss / Income Disruption',
    description:
      'Sudden layoff or reduction in hours requiring you to cover expenses with limited or no employment income.',
    probability: 8,
    impact: 95,
    riskLevel: 'high',
    category: 'Income',
    estimatedCost: 15000,
    preparednessScore: 48,
    tags: ['income', 'employment', 'financial'],
    lastUpdated: '2026-05-15',
    monthlyImpact: 1250,
    daysUntil: undefined,
  },
  {
    id: 'scenario-004',
    title: 'Rent Increase',
    description:
      "Landlord raises rent at lease renewal above your current budget, requiring you to either absorb costs or relocate.",
    probability: 45,
    impact: 55,
    riskLevel: 'medium',
    category: 'Housing',
    estimatedCost: 2400,
    preparednessScore: 60,
    tags: ['housing', 'recurring', 'predictable'],
    lastUpdated: '2026-05-08',
    monthlyImpact: 200,
    daysUntil: 47,
  },
  {
    id: 'scenario-005',
    title: 'Pet Emergency',
    description:
      'Serious illness or injury requiring emergency veterinary care, including surgery or extended treatment.',
    probability: 18,
    impact: 50,
    riskLevel: 'medium',
    category: 'Pet',
    estimatedCost: 2800,
    preparednessScore: 25,
    tags: ['pet', 'health', 'unexpected'],
    lastUpdated: '2026-05-11',
    monthlyImpact: 233,
  },
  {
    id: 'scenario-006',
    title: 'Home Appliance Failure',
    description:
      'Major appliance (HVAC, refrigerator, washer/dryer) fails and requires replacement or costly repair.',
    probability: 30,
    impact: 35,
    riskLevel: 'low',
    category: 'Home',
    estimatedCost: 1200,
    preparednessScore: 72,
    tags: ['home', 'maintenance', 'manageable'],
    lastUpdated: '2026-05-09',
    monthlyImpact: 100,
  },
  {
    id: 'scenario-007',
    title: 'Identity Theft / Fraud',
    description:
      'Unauthorized use of financial accounts requiring dispute resolution, credit monitoring, and potential legal assistance.',
    probability: 12,
    impact: 70,
    riskLevel: 'high',
    category: 'Financial Security',
    estimatedCost: 4000,
    preparednessScore: 40,
    tags: ['fraud', 'financial', 'security'],
    lastUpdated: '2026-05-14',
    monthlyImpact: 333,
  },
  {
    id: 'scenario-008',
    title: 'Missed Paycheck',
    description:
      'Payroll processing error or employer financial difficulty delays your salary by 2–4 weeks.',
    probability: 5,
    impact: 60,
    riskLevel: 'medium',
    category: 'Income',
    estimatedCost: 3600,
    preparednessScore: 55,
    tags: ['income', 'short-term', 'cash-flow'],
    lastUpdated: '2026-05-13',
    monthlyImpact: 300,
  },
]

export const timelineEvents: TimelineEvent[] = [
  {
    id: 'evt-001',
    date: '2026-06-01',
    title: 'Lease Renewal Window Opens',
    description: 'Your lease expires July 31. Landlord typically sends renewal terms 60 days prior.',
    riskLevel: 'medium',
    category: 'Housing',
    amount: 200,
    isRecurring: false,
    status: 'upcoming',
  },
  {
    id: 'evt-002',
    date: '2026-06-15',
    title: 'Car Insurance Renewal',
    description: 'Annual premium due. Last year increased 12%. Budget for potential increase.',
    riskLevel: 'low',
    category: 'Vehicle',
    amount: 1340,
    isRecurring: true,
    status: 'upcoming',
  },
  {
    id: 'evt-003',
    date: '2026-07-04',
    title: 'Q3 Tax Estimated Payment',
    description: 'Freelance income estimated quarterly payment due to IRS.',
    riskLevel: 'medium',
    category: 'Taxes',
    amount: 850,
    isRecurring: true,
    status: 'upcoming',
  },
  {
    id: 'evt-004',
    date: '2026-07-31',
    title: 'Lease Expiration',
    description: 'Current lease term ends. Must sign renewal or begin relocation process.',
    riskLevel: 'high',
    category: 'Housing',
    amount: 0,
    isRecurring: false,
    status: 'upcoming',
  },
  {
    id: 'evt-005',
    date: '2026-08-10',
    title: 'Annual Dental Checkup',
    description: 'Insurance covers preventive care. Possible treatment costs if issues found.',
    riskLevel: 'low',
    category: 'Health',
    amount: 0,
    isRecurring: true,
    status: 'upcoming',
  },
  {
    id: 'evt-006',
    date: '2026-09-01',
    title: 'Vehicle Registration Due',
    description: 'Annual DMV registration renewal including smog check fee.',
    riskLevel: 'low',
    category: 'Vehicle',
    amount: 280,
    isRecurring: true,
    status: 'upcoming',
  },
  {
    id: 'evt-007',
    date: '2026-11-15',
    title: 'Health Insurance Open Enrollment',
    description: 'Annual opportunity to change plans. Premiums expected to increase 8–14%.',
    riskLevel: 'medium',
    category: 'Health',
    amount: 1400,
    isRecurring: true,
    status: 'upcoming',
  },
  {
    id: 'evt-008',
    date: '2026-12-20',
    title: 'Holiday Budget Peak',
    description: 'Historical spending 40% above monthly average in December.',
    riskLevel: 'low',
    category: 'Lifestyle',
    amount: 1800,
    isRecurring: true,
    status: 'upcoming',
  },
]

export const emergencyPlans: EmergencyPlan[] = [
  {
    id: 'plan-001',
    category: 'Vehicle',
    title: 'Car Breakdown Response Plan',
    steps: [
      'Contact AAA roadside assistance (membership active)',
      'Get vehicle towed to pre-vetted mechanic (Garcia Auto, 415-555-0182)',
      'Arrange alternate transportation via Lyft/BART',
      'Request written estimate before authorizing repairs',
      'File claim with extended warranty if applicable',
      'Use emergency fund allocation: up to $3,500',
    ],
    contactName: 'Garcia Auto Repair',
    contactPhone: '415-555-0182',
    estimatedCost: 3200,
    fundingSource: 'Emergency Fund',
    status: 'partial',
  },
  {
    id: 'plan-002',
    category: 'Health',
    title: 'Medical Emergency Protocol',
    steps: [
      'For life-threatening: call 911 immediately',
      'For urgent care: SF Urgent Care (open 8am–10pm)',
      'Call insurance nurse hotline before ER if possible',
      'Document all care and request itemized bills',
      'Apply for hospital financial assistance (income-based)',
      'Set up payment plan if balance exceeds $1,000',
    ],
    contactName: 'Aetna Member Services',
    contactPhone: '1-800-555-2583',
    estimatedCost: 6500,
    fundingSource: 'HSA + Emergency Fund',
    status: 'not-ready',
  },
  {
    id: 'plan-003',
    category: 'Income',
    title: 'Job Loss Survival Plan',
    steps: [
      'File for unemployment benefits within 7 days (CA EDD)',
      'Reduce non-essential spending by 35% immediately',
      'Contact landlord proactively about potential hardship',
      'Activate network: LinkedIn, former colleagues, Slack communities',
      'Review severance terms and COBRA health coverage',
      'Target job search: 10 applications/day minimum',
    ],
    estimatedCost: 15000,
    fundingSource: 'Emergency Fund + Investments',
    status: 'partial',
  },
  {
    id: 'plan-004',
    category: 'Home',
    title: 'Appliance Failure Response',
    steps: [
      'Check warranty status on Home Warranty Portal',
      'Call HomeShield warranty (covers appliances up to $2,000)',
      'Get 3 quotes before accepting repair or replacement',
      'Consider energy-efficient rebates for replacement',
    ],
    contactName: 'HomeShield Warranty',
    contactPhone: '1-888-555-7741',
    estimatedCost: 1200,
    fundingSource: 'Sinking Fund',
    status: 'ready',
  },
]

export const spendingData: SpendingDataPoint[] = [
  { month: 'Nov', actual: 4820, budget: 5150, projected: 4900 },
  { month: 'Dec', actual: 6240, budget: 5150, projected: 5800 },
  { month: 'Jan', actual: 5380, budget: 5150, projected: 5100 },
  { month: 'Feb', actual: 4990, budget: 5150, projected: 5000 },
  { month: 'Mar', actual: 5210, budget: 5150, projected: 5200 },
  { month: 'Apr', actual: 5480, budget: 5150, projected: 5300 },
  { month: 'May', actual: 5150, budget: 5150, projected: 5150 },
]

export const insights: InsightCard[] = [
  {
    id: 'insight-001',
    type: 'action',
    title: 'Build your medical emergency cushion',
    description:
      "Your medical preparedness score is 20/100 — the biggest gap in your risk profile. Adding $150/month to an HSA would put you 6 months from full coverage. Your monthly surplus makes this achievable.",
    cta: 'Set up HSA contribution',
    ctaHref: '/app/everyday/emergency-plan',
    priority: 1,
  },
  {
    id: 'insight-002',
    type: 'warning',
    title: 'Entertainment spending is 39% over budget',
    description:
      "You've overspent on entertainment 3 months in a row. Cutting back to budget for 2 months would add $236 to your emergency fund.",
    cta: 'Review spending',
    ctaHref: '/app/everyday/budget-stress-test',
    priority: 2,
  },
  {
    id: 'insight-003',
    type: 'achievement',
    title: 'Your risk score improved 13 points',
    description:
      "Since January, your overall risk score dropped from 55 to 42. You're in the best financial position you've been in since joining RiskForge.",
    priority: 3,
  },
  {
    id: 'insight-004',
    type: 'tip',
    title: 'Rent renewal is 47 days away',
    description:
      "Start researching comparable rents now so you have negotiation leverage. Comparable units in your area are running $50–180 more than your current rate.",
    cta: 'View timeline',
    ctaHref: '/app/everyday/timeline',
    priority: 4,
  },
]

export const aiMessages: AIMessage[] = [
  {
    id: 'msg-001',
    role: 'assistant',
    content:
      "Hi Alex! I'm your RiskForge Coach. I've analyzed your financial profile and risk scenarios. What would you like to work on today? Here are a few areas I'd suggest:\n\n• Your medical emergency fund has the biggest gap\n• Your lease renewal is coming up in 47 days\n• Entertainment spending has been consistently over budget",
    timestamp: '2026-05-21T09:00:00',
  },
  {
    id: 'msg-002',
    role: 'user',
    content: "What should I do about my medical emergency coverage? I'm worried about the cost.",
    timestamp: '2026-05-21T09:01:00',
  },
  {
    id: 'msg-003',
    role: 'assistant',
    content:
      "Great question. Your current preparedness score for medical emergencies is 20/100 — which means you'd cover only about $1,300 of a potential $6,500 event.\n\nHere's your best path forward:\n\n**1. Open an HSA (Health Savings Account)**\nSince you have a high-deductible health plan, you can contribute up to $4,150/year pre-tax. This directly reduces your taxable income AND builds your medical buffer.\n\n**2. Start with $150/month**\nYour monthly surplus is $2,050. Setting aside $150 is only 7% of your surplus. In 8 months you'd have $1,200 saved — cutting your gap by 40%.\n\n**3. Get itemized bills**\nAlways request itemized billing after any medical care. Average billing error rate is 80% — many overcharges are catchable.\n\nWant me to walk you through setting up the HSA contribution in your budget?",
    timestamp: '2026-05-21T09:01:30',
  },
]
