import type {
  PortfolioHolding,
  RiskMetrics,
  StressTest,
  ProAlert,
  VolatilityDataPoint,
  AllocationSlice,
  RiskHeatmapCell,
  WatchlistItem,
  BusinessRisk,
} from '@/types'

export const portfolioHoldings: PortfolioHolding[] = [
  {
    id: 'h-001',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    assetClass: 'equity',
    weight: 14.2,
    value: 142000,
    quantity: 115,
    avgCost: 845.00,
    currentPrice: 1234.78,
    dayChange: 18.42,
    dayChangePct: 1.51,
    beta: 1.72,
    volatility: 42.3,
    riskContribution: 18.9,
    sector: 'Technology',
    region: 'US',
  },
  {
    id: 'h-002',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    assetClass: 'equity',
    weight: 11.8,
    value: 118000,
    quantity: 290,
    avgCost: 310.50,
    currentPrice: 406.89,
    dayChange: -2.14,
    dayChangePct: -0.52,
    beta: 0.91,
    volatility: 22.1,
    riskContribution: 9.4,
    sector: 'Technology',
    region: 'US',
  },
  {
    id: 'h-003',
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF',
    assetClass: 'equity',
    weight: 18.5,
    value: 185000,
    quantity: 365,
    avgCost: 440.00,
    currentPrice: 506.71,
    dayChange: 3.22,
    dayChangePct: 0.64,
    beta: 1.00,
    volatility: 18.2,
    riskContribution: 12.8,
    sector: 'Diversified',
    region: 'US',
  },
  {
    id: 'h-004',
    symbol: 'BTC-USD',
    name: 'Bitcoin',
    assetClass: 'crypto',
    weight: 8.4,
    value: 84000,
    quantity: 1.28,
    avgCost: 41800.00,
    currentPrice: 65625.00,
    dayChange: -840.00,
    dayChangePct: -1.27,
    beta: 2.45,
    volatility: 68.4,
    riskContribution: 22.1,
    region: 'Global',
  },
  {
    id: 'h-005',
    symbol: 'AMZN',
    name: 'Amazon.com Inc',
    assetClass: 'equity',
    weight: 9.2,
    value: 92000,
    quantity: 490,
    avgCost: 145.00,
    currentPrice: 187.76,
    dayChange: 1.88,
    dayChangePct: 1.01,
    beta: 1.14,
    volatility: 28.6,
    riskContribution: 8.6,
    sector: 'Consumer Discretionary',
    region: 'US',
  },
  {
    id: 'h-006',
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    assetClass: 'equity',
    weight: 7.6,
    value: 76000,
    quantity: 170,
    avgCost: 360.00,
    currentPrice: 447.06,
    dayChange: 4.12,
    dayChangePct: 0.93,
    beta: 1.19,
    volatility: 22.8,
    riskContribution: 7.2,
    sector: 'Technology',
    region: 'US',
  },
  {
    id: 'h-007',
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    assetClass: 'commodities',
    weight: 6.3,
    value: 63000,
    quantity: 298,
    avgCost: 190.00,
    currentPrice: 211.41,
    dayChange: 0.87,
    dayChangePct: 0.41,
    beta: -0.08,
    volatility: 14.2,
    riskContribution: 2.8,
    sector: 'Commodities',
    region: 'Global',
  },
  {
    id: 'h-008',
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury',
    assetClass: 'fixed-income',
    weight: 10.2,
    value: 102000,
    quantity: 1050,
    avgCost: 110.00,
    currentPrice: 97.14,
    dayChange: -0.42,
    dayChangePct: -0.43,
    beta: -0.22,
    volatility: 16.8,
    riskContribution: 3.1,
    sector: 'Bonds',
    region: 'US',
  },
  {
    id: 'h-009',
    symbol: 'ETH-USD',
    name: 'Ethereum',
    assetClass: 'crypto',
    weight: 4.8,
    value: 48000,
    quantity: 13.5,
    avgCost: 2100.00,
    currentPrice: 3555.56,
    dayChange: -62.00,
    dayChangePct: -1.72,
    beta: 2.18,
    volatility: 72.1,
    riskContribution: 11.2,
    region: 'Global',
  },
  {
    id: 'h-010',
    symbol: 'CASH',
    name: 'Cash & Money Market',
    assetClass: 'cash',
    weight: 9.0,
    value: 90000,
    quantity: 90000,
    avgCost: 1.00,
    currentPrice: 1.00,
    dayChange: 0,
    dayChangePct: 0,
    beta: 0,
    volatility: 0,
    riskContribution: 0,
  },
]

export const riskMetrics: RiskMetrics = {
  portfolioVaR95: -47200,
  portfolioVaR99: -72800,
  cVar: -84500,
  sharpeRatio: 1.42,
  sortino: 1.87,
  maxDrawdown: -18.6,
  beta: 0.94,
  alpha: 3.2,
  trackingError: 8.4,
  informationRatio: 0.38,
  volatility: 19.8,
}

export const stressTests: StressTest[] = [
  {
    id: 'st-001',
    name: '2008 Financial Crisis',
    description: 'Simulates the conditions of the 2008–2009 global financial crisis with peak-to-trough drawdowns.',
    scenario: 'S&P 500 drops 55%, credit spreads widen 650bps, crypto effectively zero, gold +25%',
    portfolioImpact: -412000,
    portfolioImpactPct: -41.2,
    worstHolding: 'BTC-USD (-98%)',
    bestHolding: 'GLD (+25%)',
    probability: 'Low (3–5% in 1Y)',
    historicalPrecedent: '2008–2009',
    holdingsImpact: [
      { symbol: 'NVDA', impact: -138000, impactPct: -97.2 },
      { symbol: 'BTC-USD', impact: -82320, impactPct: -98.0 },
      { symbol: 'SPY', impact: -101750, impactPct: -55.0 },
      { symbol: 'GLD', impact: 15750, impactPct: 25.0 },
      { symbol: 'TLT', impact: 18360, impactPct: 18.0 },
    ],
  },
  {
    id: 'st-002',
    name: '2022 Rate Shock',
    description: 'Fed raises rates 400bps over 12 months causing equity/bond correlation to break down.',
    scenario: 'Growth equities -40%, bonds -25%, crypto -70%, commodities +15%',
    portfolioImpact: -198000,
    portfolioImpactPct: -19.8,
    worstHolding: 'ETH-USD (-70%)',
    bestHolding: 'GLD (+12%)',
    probability: 'Medium (15–20% in 1Y)',
    historicalPrecedent: '2022',
    holdingsImpact: [
      { symbol: 'NVDA', impact: -56800, impactPct: -40.0 },
      { symbol: 'ETH-USD', impact: -33600, impactPct: -70.0 },
      { symbol: 'TLT', impact: -25500, impactPct: -25.0 },
      { symbol: 'GLD', impact: 7560, impactPct: 12.0 },
      { symbol: 'CASH', impact: 0, impactPct: 0 },
    ],
  },
  {
    id: 'st-003',
    name: 'Crypto Regulatory Crackdown',
    description: 'Major governments ban crypto trading, causing 90% drawdown in digital assets.',
    scenario: 'Bitcoin/ETH -90%, crypto contagion spills into growth equities -15%',
    portfolioImpact: -131200,
    portfolioImpactPct: -13.1,
    worstHolding: 'BTC-USD (-90%)',
    bestHolding: 'TLT (+8%)',
    probability: 'Low (5–8% in 1Y)',
    holdingsImpact: [
      { symbol: 'BTC-USD', impact: -75600, impactPct: -90.0 },
      { symbol: 'ETH-USD', impact: -43200, impactPct: -90.0 },
      { symbol: 'NVDA', impact: -21300, impactPct: -15.0 },
      { symbol: 'TLT', impact: 8160, impactPct: 8.0 },
    ],
  },
  {
    id: 'st-004',
    name: 'Soft Landing / Bull Run',
    description: 'Fed achieves soft landing, earnings beat expectations, markets rally 30%.',
    scenario: 'S&P +30%, tech +45%, crypto +80%, bonds -5%',
    portfolioImpact: 312000,
    portfolioImpactPct: 31.2,
    worstHolding: 'TLT (-5%)',
    bestHolding: 'BTC-USD (+80%)',
    probability: 'Medium (25–35% in 1Y)',
    holdingsImpact: [
      { symbol: 'BTC-USD', impact: 67200, impactPct: 80.0 },
      { symbol: 'NVDA', impact: 63900, impactPct: 45.0 },
      { symbol: 'SPY', impact: 55500, impactPct: 30.0 },
      { symbol: 'ETH-USD', impact: 38400, impactPct: 80.0 },
      { symbol: 'TLT', impact: -5100, impactPct: -5.0 },
    ],
  },
]

export const proAlerts: ProAlert[] = [
  {
    id: 'alert-001',
    type: 'concentration',
    severity: 'high',
    title: 'Crypto Concentration Risk',
    description: 'Combined crypto exposure (BTC + ETH) is 13.2% of portfolio, exceeding your 10% threshold.',
    metric: 'Crypto Weight',
    threshold: 10,
    currentValue: 13.2,
    triggeredAt: '2026-05-21T08:32:00',
    isRead: false,
    action: 'Consider reducing crypto allocation or setting stop-losses',
  },
  {
    id: 'alert-002',
    type: 'volatility',
    severity: 'medium',
    title: 'Portfolio Volatility Elevated',
    description: 'Realized 30-day volatility of 24.1% exceeds your 20% target by 4.1 percentage points.',
    metric: '30-Day Volatility',
    threshold: 20,
    currentValue: 24.1,
    triggeredAt: '2026-05-20T16:45:00',
    isRead: false,
    action: 'Review high-beta positions (NVDA, crypto)',
  },
  {
    id: 'alert-003',
    type: 'drawdown',
    severity: 'low',
    title: 'BTC Approaching Alert Level',
    description: 'Bitcoin is down 8.3% from its 30-day high. Alert triggers at -10%.',
    metric: 'BTC Drawdown',
    threshold: -10,
    currentValue: -8.3,
    triggeredAt: '2026-05-21T07:15:00',
    isRead: true,
    action: 'Monitor closely, consider trailing stop',
  },
  {
    id: 'alert-004',
    type: 'var_breach',
    severity: 'medium',
    title: '1-Day VaR Limit Warning',
    description: 'Current 1-day 95% VaR of $47,200 is approaching your $50,000 daily limit.',
    metric: '1-Day VaR (95%)',
    threshold: 50000,
    currentValue: 47200,
    triggeredAt: '2026-05-21T09:00:00',
    isRead: false,
    action: 'Review position sizes before market open',
  },
  {
    id: 'alert-005',
    type: 'liquidity',
    severity: 'low',
    title: 'Cash Allocation Below Target',
    description: 'Cash/liquid positions at 9.0% vs your 10% minimum liquidity target.',
    metric: 'Cash Allocation',
    threshold: 10,
    currentValue: 9.0,
    triggeredAt: '2026-05-19T14:20:00',
    isRead: true,
    action: 'Consider liquidating underperforming positions to raise cash',
  },
]

export const volatilityData: VolatilityDataPoint[] = [
  { date: '2025-11-01', portfolioVol: 16.2, benchmarkVol: 14.8, vix: 14.2 },
  { date: '2025-11-15', portfolioVol: 17.8, benchmarkVol: 15.1, vix: 15.8 },
  { date: '2025-12-01', portfolioVol: 21.4, benchmarkVol: 18.6, vix: 20.1 },
  { date: '2025-12-15', portfolioVol: 19.2, benchmarkVol: 17.3, vix: 17.4 },
  { date: '2026-01-01', portfolioVol: 18.4, benchmarkVol: 16.2, vix: 16.0 },
  { date: '2026-01-15', portfolioVol: 20.1, benchmarkVol: 17.8, vix: 18.2 },
  { date: '2026-02-01', portfolioVol: 22.6, benchmarkVol: 19.4, vix: 22.5 },
  { date: '2026-02-15', portfolioVol: 25.8, benchmarkVol: 21.2, vix: 26.1 },
  { date: '2026-03-01', portfolioVol: 23.1, benchmarkVol: 19.8, vix: 21.8 },
  { date: '2026-03-15', portfolioVol: 21.4, benchmarkVol: 18.5, vix: 19.4 },
  { date: '2026-04-01', portfolioVol: 20.2, benchmarkVol: 17.9, vix: 18.0 },
  { date: '2026-04-15', portfolioVol: 22.4, benchmarkVol: 19.1, vix: 21.3 },
  { date: '2026-05-01', portfolioVol: 23.8, benchmarkVol: 20.4, vix: 23.1 },
  { date: '2026-05-15', portfolioVol: 24.1, benchmarkVol: 20.8, vix: 24.4 },
  { date: '2026-05-21', portfolioVol: 24.1, benchmarkVol: 20.8, vix: 24.4 },
]

export const assetAllocation: AllocationSlice[] = [
  { name: 'US Equities', value: 61.3, color: '#4f8ef7' },
  { name: 'Crypto', value: 13.2, color: '#f59e0b' },
  { name: 'Fixed Income', value: 10.2, color: '#10b981' },
  { name: 'Cash', value: 9.0, color: '#64748b' },
  { name: 'Commodities', value: 6.3, color: '#38bdf8' },
]

export const riskHeatmap: RiskHeatmapCell[] = [
  { row: 'NVDA', col: 'MSFT', value: 0.62, label: '0.62' },
  { row: 'NVDA', col: 'SPY', value: 0.74, label: '0.74' },
  { row: 'NVDA', col: 'BTC', value: 0.38, label: '0.38' },
  { row: 'NVDA', col: 'GLD', value: -0.12, label: '-0.12' },
  { row: 'NVDA', col: 'TLT', value: -0.31, label: '-0.31' },
  { row: 'MSFT', col: 'SPY', value: 0.81, label: '0.81' },
  { row: 'MSFT', col: 'BTC', value: 0.29, label: '0.29' },
  { row: 'MSFT', col: 'GLD', value: -0.08, label: '-0.08' },
  { row: 'MSFT', col: 'TLT', value: -0.18, label: '-0.18' },
  { row: 'SPY', col: 'BTC', value: 0.41, label: '0.41' },
  { row: 'SPY', col: 'GLD', value: 0.05, label: '0.05' },
  { row: 'SPY', col: 'TLT', value: -0.42, label: '-0.42' },
  { row: 'BTC', col: 'GLD', value: 0.22, label: '0.22' },
  { row: 'BTC', col: 'TLT', value: -0.15, label: '-0.15' },
  { row: 'GLD', col: 'TLT', value: 0.31, label: '0.31' },
]

export const watchlist: WatchlistItem[] = [
  {
    symbol: 'TSLA',
    name: 'Tesla Inc',
    price: 184.22,
    change: -4.18,
    changePct: -2.22,
    volume: '98.4M',
    marketCap: '$587B',
    riskScore: 72,
    riskLevel: 'high',
    alert: 'Approaching 52-week low',
  },
  {
    symbol: 'META',
    name: 'Meta Platforms',
    price: 512.34,
    change: 6.82,
    changePct: 1.35,
    volume: '24.1M',
    marketCap: '$1.31T',
    riskScore: 45,
    riskLevel: 'medium',
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc',
    price: 174.88,
    change: 1.14,
    changePct: 0.66,
    volume: '22.8M',
    marketCap: '$2.18T',
    riskScore: 38,
    riskLevel: 'low',
  },
  {
    symbol: 'SOL-USD',
    name: 'Solana',
    price: 168.42,
    change: -8.24,
    changePct: -4.66,
    volume: '4.2B',
    marketCap: '$78.1B',
    riskScore: 88,
    riskLevel: 'critical',
    alert: 'High volatility: 78% annualized',
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies',
    price: 28.14,
    change: 0.88,
    changePct: 3.23,
    volume: '48.2M',
    marketCap: '$60.1B',
    riskScore: 65,
    riskLevel: 'high',
  },
]

export const businessRisks: BusinessRisk[] = [
  {
    id: 'br-001',
    category: 'Market Risk',
    title: 'Key Customer Concentration',
    description: 'Top 3 customers represent 62% of ARR. Loss of any one would require 14+ months to replace.',
    likelihood: 25,
    impact: 85,
    riskScore: 71,
    riskLevel: 'high',
    owner: 'VP Sales',
    mitigations: [
      'Active diversification strategy targeting <50% concentration',
      'Quarterly business reviews with top accounts',
      'Multi-year contract renewals in progress',
    ],
    status: 'assessed',
    reviewDate: '2026-06-01',
  },
  {
    id: 'br-002',
    category: 'Operational Risk',
    title: 'Key Person Dependency',
    description: 'CTO is sole holder of critical infrastructure knowledge. No documented succession plan.',
    likelihood: 15,
    impact: 90,
    riskScore: 68,
    riskLevel: 'high',
    owner: 'CEO',
    mitigations: [
      'Documentation sprint scheduled Q3',
      'Cross-training program initiated',
    ],
    status: 'identified',
    reviewDate: '2026-07-01',
  },
  {
    id: 'br-003',
    category: 'Financial Risk',
    title: 'Runway Below 12 Months',
    description: 'Current burn rate gives 10.2 months of runway without additional revenue or funding.',
    likelihood: 40,
    impact: 95,
    riskScore: 82,
    riskLevel: 'critical',
    owner: 'CFO',
    mitigations: [
      'Series B fundraise in progress (3 term sheets)',
      'Cost reduction plan identifies $280k in savings',
      'Two enterprise deals in late-stage negotiation',
    ],
    status: 'monitored',
    reviewDate: '2026-06-15',
  },
  {
    id: 'br-004',
    category: 'Compliance Risk',
    title: 'Data Privacy Compliance Gap',
    description: 'GDPR and CCPA audit identified 4 medium and 1 high-severity findings requiring remediation.',
    likelihood: 60,
    impact: 55,
    riskScore: 58,
    riskLevel: 'medium',
    owner: 'General Counsel',
    mitigations: [
      'Privacy officer hired (starts June 1)',
      'Data audit and mapping underway',
      'Legal review of data handling contracts',
    ],
    status: 'mitigated',
    reviewDate: '2026-08-01',
  },
]

export const portfolioSummary = {
  totalValue: 1000000,
  dayChange: -2840,
  dayChangePct: -0.28,
  weekChange: 18400,
  weekChangePct: 1.87,
  monthChange: -24100,
  monthChangePct: -2.35,
  yearChange: 187200,
  yearChangePct: 23.0,
  riskScore: 68,
  liquidityRatio: 0.19,
  concentrationRisk: 'high',
  beta: 0.94,
}
