/**
 * Scenario bundles — curated collections of scenarios that commonly co-occur.
 * Used to let users run a realistic "life package" with a single click.
 */

import type { ScenarioBundle } from './types'

export const BUNDLES: ScenarioBundle[] = [
  {
    id: 'bundle-everyday-starter',
    name: 'Everyday Starter Pack',
    description: 'The most common financial hits that happen to most people at some point.',
    emoji: '📦',
    color: '#4f8ef7',
    tier: 'everyday',
    scenarioIds: [
      'car-minor-repair',
      'pet-emergency',
      'grocery-spike',
      'urgent-care',
      'subscription-creep',
      'utility-spike',
      'multiple-small-things',
    ],
  },
  {
    id: 'bundle-renter',
    name: 'Renter Risk Pack',
    description: 'Everything that can go wrong when you don\'t own your home.',
    emoji: '🏠',
    color: '#f59e0b',
    tier: 'everyday',
    scenarioIds: [
      'rent-increase',
      'forced-move',
      'roommate-leaves',
      'appliance-failure',
      'pest-infestation',
      'utility-spike',
      'subscription-creep',
    ],
  },
  {
    id: 'bundle-homeowner',
    name: 'Homeowner Risk Pack',
    description: 'The major systems and surprises that come with owning property.',
    emoji: '🔧',
    color: '#f97316',
    tier: 'everyday',
    scenarioIds: [
      'hvac-failure',
      'plumbing-emergency',
      'appliance-failure',
      'pest-infestation',
      'mortgage-payment-shock',
      'power-outage-extended',
    ],
  },
  {
    id: 'bundle-pet-parent',
    name: 'Pet Parent Pack',
    description: 'Vet bills, ongoing care, and the financial reality of pet ownership.',
    emoji: '🐾',
    color: '#a78bfa',
    tier: 'everyday',
    scenarioIds: [
      'pet-emergency',
      'pet-surgery',
      'pet-medication-ongoing',
      'multiple-small-things',
    ],
  },
  {
    id: 'bundle-freelancer',
    name: 'Freelancer / Creator Pack',
    description: 'Income volatility, tax surprises, and platform risks for self-employed users.',
    emoji: '💼',
    color: '#10b981',
    tier: 'everyday',
    scenarioIds: [
      'client-loss-freelancer',
      'self-employment-tax-shock',
      'platform-income-disruption',
      'reduced-hours',
      'insurance-gap',
      'credit-card-emergency',
    ],
  },
  {
    id: 'bundle-family',
    name: 'Family Pack',
    description: 'Financial shocks that come with having kids, partners, and extended family.',
    emoji: '👨‍👩‍👧',
    color: '#38bdf8',
    tier: 'everyday',
    scenarioIds: [
      'childcare-increase',
      'family-emergency-travel',
      'emergency-room',
      'dental-emergency',
      'student-loan-return',
      'second-earner-loss',
    ],
  },
  {
    id: 'bundle-fragile-cashflow',
    name: 'Fragile Cashflow Pack',
    description: 'The spiral that happens when there\'s no buffer: fees, interest, and missed payments.',
    emoji: '⚠️',
    color: '#ef4444',
    tier: 'everyday',
    scenarioIds: [
      'credit-card-emergency',
      'bnpl-stackup',
      'missed-payment-spiral',
      'grocery-spike',
      'multiple-small-things',
      'subscription-creep',
    ],
  },
  {
    id: 'bundle-gulf-coast',
    name: 'Gulf Coast / Hurricane Belt',
    description: 'Coastal disaster risks plus the insurance and recovery aftermath.',
    emoji: '🌀',
    color: '#6366f1',
    tier: 'everyday',
    scenarioIds: [
      'hurricane-evacuation',
      'power-outage-extended',
      'plumbing-emergency',
      'utility-spike',
      'appliance-failure',
      'identity-theft',
    ],
  },
  {
    id: 'bundle-investor-collision',
    name: 'Investor Life Collision',
    description: 'When life events force you to sell investments at the worst time.',
    emoji: '📉',
    color: '#f59e0b',
    tier: 'pro',
    scenarioIds: [
      'job-loss-long',
      'macro-gfc-2008',
      'emergency-room',
      'breakup-housing-shock',
      'portfolio-sequence-risk',
    ],
  },
  {
    id: 'bundle-pro-trader',
    name: 'Pro Trader Stress Kit',
    description: 'Market structure risks that test concentrated, leveraged, or momentum strategies.',
    emoji: '📊',
    color: '#a78bfa',
    tier: 'pro',
    scenarioIds: [
      'portfolio-deep-bear',
      'portfolio-volatility-spike',
      'portfolio-concentrated-crash',
      'macro-crypto-winter',
      'macro-svb-2023',
    ],
  },
  {
    id: 'bundle-macro-history',
    name: 'Historical Macro Gauntlet',
    description: 'Run your portfolio through the 5 worst macro shocks of the last 25 years.',
    emoji: '🏛️',
    color: '#64748b',
    tier: 'pro',
    scenarioIds: [
      'macro-dot-com-2000',
      'macro-gfc-2008',
      'macro-covid-2020',
      'macro-inflation-2022',
      'macro-tariff-shock',
    ],
  },
]

export const BUNDLES_BY_ID = new Map(BUNDLES.map((b) => [b.id, b]))
